### PR TITLE
Use <OutboundLink> for <LogoutLink>

### LINKED ISSUE #1613: track logouts using an OutboundLink component rather than <a>
We track login events via GA at the moment, but not logout events; it'll be good to add an event signal to the LogoutLink component so that we can see the number of logouts per timeunit in addition to logins.

### PR DESCRIPTION
**Pull request by mmmavis**
Fixes #1613

### CODE REVIEW

**Comment by mmmavis** [comment]
Travis is failing. Let me update my PR.

**Comment by mmmavis** [comment]
Updated!

**Comment by Pomax** [comment]
r+

**Comment by mmmavis** [comment]
Yeah Yeah Yeah :v:

**Pull request merged**
