### PR TITLE
Tag and release v0.0.29

### PR DESCRIPTION
**Pull request by mmmavis**
### Changed
- Updated dependencies including uplifting React to v0.14 and other packages.
- Started UI unification work.
- Updated page banners across the site.

### Added
- Added Webmaker activity kit.
- Added Community page.

### CODE REVIEW

**Comment by mmmavis** [comment]
@hannahkane r+? :bowtie:

**Comment by hannahkane** [comment]
Banners, Community, and Webmaker kit look great. R+

**Comment by mmmavis** [comment]
:tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: 
LAST RELEASE OF YEAR 2015
:dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers:

**Comment by hannahkane** [comment]
My party hat is off to you, @mmmavis!

**Pull request merged**
