### PR TITLE
Turn off auto push to s3 for develop branch

### PR DESCRIPTION
**Pull request by alicoding**

### CODE REVIEW

**Comment by alicoding** [comment]
@cadecairos or @Pomax R?

**Comment by cadecairos** [comment]
R+

**Comment by Pomax** [comment]
did you check to make sure that the values you just took out are properly reflected on the new heroku staging app, though?

**Comment by cadecairos** [comment]
Yes, the configs are identical

**Comment by Pomax** [comment]
awesome :+1:

**Pull request merged**
