### PR TITLE
npm install mozilla-tabzilla

### LINKED ISSUE #1504: Install Tabzilla using npm instead
New Tabzilla was out a few months ago. We should update & install Tabzilla used on our site via npm instead.
See instructions [here](https://github.com/mozilla/tabzilla/#npm).

This following error should go away once we update Tabzilla.
screen shot 2015-12-21 at 2 52 11 pm

### PR DESCRIPTION
**Pull request by mmmavis**
Fixes #1504

### CODE REVIEW

**Comment by mmmavis** [comment]
@sabrinang @kristinashu should we give the wordmark a colour? Default is transparent. Will body text colour `#4D4E53` work?

**Comment by kristinashu** [comment]
I think it's kinda cool having it transparent. @sabrinang?

**Comment by mmmavis** [comment]
@sabrinang @kristinashu the new Tabzilla looks like https://github.com/mozilla/tabzilla/#changing-the-color-of-the-wordmark.  It's flat and doesn't have shadow around it. So if it's on pages like https://teach.mozilla.org/events/resources/ Tabzilla will not be visible.

**Comment by kristinashu** [comment]
Oh I see, body text colour works for me. Thanks!

**Comment by sabrinang** [comment]
:+1: cool, body text colour sounds good since it'll be white on white

**Comment by Pomax** [comment]
R+ from a code perspective =)

**Pull request merged**
