### PR TITLE
Tag and release v0.0.22

### PR DESCRIPTION
**Pull request by mmmavis**
### Added
- The pledge modal on the homepage pops up automatically for users who 
  visit the site for the first time.
- Check out the "Quacking JavaScript" module that we added to the 
  Teaching Activities page.

### Changed
- The Clubs Toolkit page has been removed. New guides are coming soon so
  stay tuned.
- Updated Thimble's sample activity listed on the Tools page.
- The About page has been refreshed.
- We can now track outbound links from the Tools page to each tool listed there.
- Removed Creative Commons license note from Teaching Activites pages due to 
  change in policy by Legal to no longer require that particular license.
- The GitHub repo name has been renamed from teach.webmaker.org
  to teach.mozilla.org. This shouldn't affect anything to end users.

### CODE REVIEW

**Comment by mmmavis** [comment]
@hannahkane a new release for you to review before I push it live!

**Comment by hannahkane** [comment]
R+

**Comment by hannahkane** [comment]
also: :fireworks:

**Comment by mmmavis** [comment]
:tada: :clap:

**Pull request merged**
