### PR TITLE
adding May curriculum workshop details and updating archives

### LINKED ISSUE #1838: Update Curriculum Workshop page
@chadsansing @amirad - do you have details about the next Curriculum Workshop yet?

When you have it, drop it here and we'll update the site. Thanks!

### PR DESCRIPTION
**Pull request by hannahkane**
Fixes #1838 

**Changes proposed in this pull request:**
- adds May workshop details to landing page
- adds archive page for April workshop
- updates "upcoming workshops" section of March archive page

cc @flukeout  - R?

### CODE REVIEW

**Comment by hannahkane** [comment]
@flukeout - it's going to be difficult to maintain an accurate "upcoming workshops" list on every individual archive page. Wondering if we should replace that with a link to the landing page instead.

**Comment by flukeout** [comment]
That we can agree on - I thought I'd actually removed them from the current archive pages. I think we can just ditch all of the upcoming workshop info from the archives altogether.

**Comment by hannahkane** [comment]
K. I can do that now.

**Comment by flukeout** [comment]
Nice

**Comment by hannahkane** [comment]
@flukeout - how about now?

**Comment by flukeout** [comment]
Looks good!

**Comment by flukeout** [comment]
@Pomax what's our stance on squashing PRs into one committ?

**Comment by hannahkane** [comment]
whoops, sorry if I did something wrong. what should I have done instead?

**Comment by flukeout** [comment]
@hannahkane No worries - sorry I should have added some detail. 

Generally a good practice for PRs is to have all of the changes in one commit. It makes it easier to keep track of the history of what's happened to the code base.

Squashing is a techniqe to basically take all of the commits you have and package them under one. I can show you how to do that - ping me on mattermoz.

**Comment by flukeout** [comment]
Okay nice - good to go.

**Comment by KGorr** [comment]
@hannahkane @flukeout any ETA on when this will be live so that social media promotion of the upcoming workshop can be shared? Thanks!

**Comment by hannahkane** [comment]
@KGorr - aiming to push to production later today

**Comment by KGorr** [comment]
perfect - thanks for the update!

**Pull request merged**
