### PR TITLE
Tag and release v0.0.39

### PR DESCRIPTION
**Pull request by mmmavis**
### Changed
- Fixed Web Literacy Map data since Synthesize, Share and Connect were
  assgined the wrong 21st century skills.
- Unified button, label, and link styles across the site.
- Fixed url-to-react-router-path rewriter so that hitting pages with hash 
  and/or query string in the URL won't result in 404.

### CODE REVIEW

**Comment by mmmavis** [comment]
@hannahkane r?

**Comment by hannahkane** [comment]
r+

**Comment by mmmavis** [comment]
merging! :tada:

**Comment by hannahkane** [comment]
yay! thanks!

**Pull request merged**
