### PR TITLE
Tag and release v0.0.25

### PR DESCRIPTION
**Pull request by mmmavis**
### Added
- Added "Privacy Basics" activity.

### Changed
- Cleaned up some LESS code by introducing a pageColorizer mixin.
- Removed code used for an old A/B testing.
- We are now using mocha-phantomjs v4.* 
- Bumped npm module lwip version from 0.0.5 to 0.0.8.

### CODE REVIEW

**Comment by mmmavis** [comment]
@hannahkane r+?

**Comment by hannahkane** [comment]
Some things are off in the Privacy Kit. I'll note them on the relevant ticket.

**Comment by mmmavis** [comment]
@hannahkane can you reference the ticket number here?

**Comment by hannahkane** [comment]
#1353. Need to fix one link; otherwise the problems are with the linked pages themselves. @chadsansing - let me know if you need help with those.

**Comment by hannahkane** [comment]
Disregard #1353. But please do fix https://github.com/mozilla/teach.mozilla.org/issues/1404 before releasing.

**Comment by mmmavis** [comment]
closing this now.  gonna create a new PR.

**Pull request closed without merging**
