### PR TITLE
/me page

### LINKED ISSUE #1276: Implement /me page
This page will be a place for webmaker users to view their makes, once we shut down the legacy Webmaker site.

Blocked on design in #1265 

I'm not too familiar with the teach tech stack, but it sounds like we need to load and display makes client side.

### PR DESCRIPTION
**Pull request by mmmavis**
Fixes #1276
All Makes are listed in a single page (no pagination).

-----
Todo after this PR gets merged

- rename `makes.jsx` to `me.jsx`

### CODE REVIEW

**Comment by cadecairos** [comment]
woo!, this is looking great

**Comment by cadecairos** [comment]
It looks like we need to sort by updatedAt by adding `&sortByField=updatedAt` near the top of pages/makes.jsx

**Comment by mmmavis** [comment]
@cadecairos I updated the PR again! Let me know how I should proceed once the MakeAPI stuff that you and @jbuck mentioned has been sorted out. :+1:

**Comment by jbuck** [comment]
@mmmavis Try using https://jon.mywebmaker.org/makes.json as a data source!

Replace my username with any valid staging username.

This will work on https://jon.makes.org/makes.json tomorrow

**Comment by mmmavis** [comment]
@cadecairos review again? :grin: (currently missing a fallback image for thumbnail but I will add it back once the file is ready)

**Comment by cadecairos** [comment]
@mmmavis looks and functions great!

Just a thought: should we collapse the menu when navigating away from a page?

**Comment by mmmavis** [comment]
@cadecairos 

> Just a thought: should we collapse the menu when navigating away from a page?

I like that idea! Though I'd prefer to file a separate ticket for that since the sidebar code needs some rewrite to make this happen.  Let's just get this PR out and worry about tweaks later? I'll file a ticket!

I just added in the fallback image for Makes without a thumbnail.  Once I see the green light from Travis I'll merge this PR :dancer: This will be live on staging soon!

**Comment by mmmavis** [comment]
:dancers: :dancers: :dancers: :dancers: :dancers: thanks team!

**Pull request merged**
