### PR TITLE
fixes #1776 by changing a link

### LINKED ISSUE #1776: Update activity link on teach.mozilla.org/activities
Here is the new link (in new Thimble) for the Hack My Media activity - featured on both teach.mozilla.org/activities and goggles.mozilla.org

https://thimbleprojects.org/stephguthrie/48361/

### PR DESCRIPTION
**Pull request by hannahkane**
Fixes #1776

Not sure if it's something I did, but the image widths are no longer fixed on the /activities page. Sorry if I did that. :(

### CODE REVIEW

**Comment by hannahkane** [comment]
@Pomax or @mmmavis - could one of you please review this tiny change and confirm whether I broke the images in any way? (I didn't touch them, afaik)

**Comment by mmmavis** [comment]
@hannahkane could you attach a screen cap of the image width problem?

**Comment by hannahkane** [comment]
screen shot 2016-03-31 at 1 23 11 pm

**Comment by mmmavis** [comment]
r+
the image width issue isn't related to this PR. I think it's introduced by the change in https://github.com/mozilla/teach.mozilla.org/commit/99672d323b35f2caf3b22b0f205f5319abb03080#diff-9fb9a1085ade89fb217c95df87a638cf . I'll file a ticket.

**Pull request merged**
