### PR TITLE
[WIP] Some accessibility fixes for modals

### PR DESCRIPTION
**Pull request by toolness**
This makes some a11y fixes for our modals (some specific to club modals):

* The close box for our modals was just being announced as "button"; now it's "Close button".
* The "a network error occurred" and "your submission has some problems" alerts on our modals aren't announced by screen readers because they don't have `role="alert"` on them, which is now fixed. Also, NVDA doesn't seem to announce any `<ul>`'s within alerts, so I had to convert the lists to paragraphs. Which seems dumb, but I guess it's better than not announcing them at all?
* The "Add Your Club" button on the Clubs page was a link instead of a `<button>`, and because it didn't have a `href` attribute, it wasn't focusable with the keyboard. I changed it to a `<button>`.
* The club location autocomplete field now has a `<label>` associated with it.
* Changes between individual steps of the modal, e.g. going from the "add your club" form step to the "thanks for your submission" step, weren't announced by screen readers. We now define [ARIA Live Regions](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions) so this is fixed.
* The way input focus was being handled between opening and closing the modal, and navigating between the individual steps in a modal, was terrible. I had no idea where my input focus was during these transitions, and often it was in an invalid place, e.g. still on the "Add My Club" button when the "Add Your Club" modal is in focus. I've fixed this so that, at the very least, the modal itself becomes focused when shown, and the DOM element that had focus before it was shown is re-focused when the modal closes. Also, a `StepView` component for multi-step modals has been added, which manages the auto-focusing of elements as users transition into a new step.

Other notes:

* The club location autocomplete field isn't very accessible to screen-readers, though at least it's fully usable via keyboard. Not really sure if this can be fixed without altering [`react-select`](https://github.com/JedWatson/react-select) and there don't seem to be any issues in that project about accessibility, aside from the delete button being pronounced "times". 

Things still left to do:

* I should add unit tests for some of this stuff, but I'm holding off on it until we've done some QA and verified that this is the behavior we want.

### CODE REVIEW

**Comment by toolness** [comment]
@mmmavis can you take a look at this using VoiceOver and verify that these changes work OK? I've only tested on NVDA so far and could use a second opinion.

**Comment by mmmavis** [comment]
yup yup! should i check out this PR or the `develop` branch?

**Comment by toolness** [comment]
oh this pr please. you can compare how it works on screenreaders/with keyboard against staging if you like.

**Comment by toolness** [comment]
Hey any chance you could get around to testing this on VoiceOver soon? If you think the fixes are usable then I will bust up unit tests!

**Comment by mmmavis** [comment]
@toolness oh yea sorry, checking it out now

**Comment by mmmavis** [comment]
> This makes some a11y fixes for our modals (some specific to club modals):
* The close box for our modals was just being announced as "button"; now it's "Close button".

:+1: with VoiceOver

> * The "a network error occurred" and "your submission has some problems" alerts on our modals aren't announced by screen readers because they don't have `role="alert"` on them, which is now fixed. Also, NVDA doesn't seem to announce any `<ul>`'s within alerts, so I had to convert the lists to paragraphs. Which seems dumb, but I guess it's better than not announcing them at all?

VoiceOver reads it as "Window" and I can't get inside of the div :disappointed:  It's the same if I change them back to list form. 

> * The "Add Your Club" button on the Clubs page was a link instead of a `<button>`, and because it didn't have a `href` attribute, it wasn't focusable with the keyboard. I changed it to a `<button>`.
* The club location autocomplete field now has a `<label>` associated with it.
* Changes between individual steps of the modal, e.g. going from the "add your club" form step to the "thanks for your submission" step, weren't announced by screen readers. We now define [ARIA Live Regions](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions) so this is fixed.

After the form has been successfully submitted, VoiceOver reads the button text "Take Me To My Club" and skips everything else.  :confused: 

> * The way input focus was being handled between opening and closing the modal, and navigating between the individual steps in a modal, was terrible. I had no idea where my input focus was during these transitions, and often it was in an invalid place, e.g. still on the "Add My Club" button when the "Add Your Club" modal is in focus. I've fixed this so that, at the very least, the modal itself becomes focused when shown, and the DOM element that had focus before it was shown is re-focused when the modal closes. Also, a `StepView` component for multi-step modals has been added, which manages the auto-focusing of elements as users transition into a new step.

Works :+1: with VoiceOver and keyboard.

**Comment by toolness** [comment]
Ok, so [`role="alert"` is extremely frustrating](http://www.paciellogroup.com/blog/2012/06/html5-accessibility-chops-aria-rolealert-browser-support/) because it works *so differently* across different browser/screenreader combinations that getting it to work in one makes it break in another. In https://github.com/mozilla/teach.webmaker.org/commit/8720213ff825d00a293803fe1b66323fff5bc3a4 I implemented a weird, kludgy work-around that got things to work on OS X Safari+Chrome, but that broke things in NVDA on Windows, so I reverted the changes in https://github.com/mozilla/teach.webmaker.org/commit/13142d4509a1d61f434a8a05369b8244bb047bae, as it's easier to just keep the code as simple as possible and rely on UA vendors to make `role="alert"` work in a consistent way that doesn't drive developers insane.

Since the current PR doesn't *degrade* VoiceOver performance but improves NVDA performance, I think we should leave the behavior as-is and just add unit tests for what we've got here and land these changes. What do you think @mmmavis ?

**Comment by toolness** [comment]
Hey @mmmavis, any idea when you might be able to get to this?

**Comment by mmmavis** [comment]
Sorry @toolness I missed [your ping earlier](https://github.com/mozilla/teach.webmaker.org/pull/1034#issuecomment-116667642).  I will get to this today :bowtie: (btw, is this still WIP? :grin: )

**Comment by toolness** [comment]
Yeah, it's still WIP, I just wanted to know what your opinion on [my last comment](https://github.com/mozilla/teach.webmaker.org/pull/1034#issuecomment-116667642) was. If you're ok w/ the current behavior then I will start writing tests!

**Comment by mmmavis** [comment]
cool, i'll check this out after the standups.

**Comment by mmmavis** [comment]
Hey @toolness , thanks for sharing links to those useful posts. :wink:  It's very challenging to make a11y work across browsers/platform/screen readers so I'm fine with your solution here. (thanks for working on this!)

I know we haven't decided on [our browser support](https://github.com/mozilla/teach.webmaker.org/issues/151) but a11y-wise I'm wondering if we should focus on just a few platform combos(e.g., FF on Mac OSX with VoiceOver, Chrome on Windows with NVDA... something like that).  It's :disappointed: to say this but if we are too committed to making the site widely accessible I'm worried it will lead to dev overhead. :no_mouth:

**Comment by Pomax** [comment]
closing, as the codebase has passed this PR by significantly.

**Pull request closed without merging**
