### PR TITLE
Tag and release v0.0.27

### PR DESCRIPTION
**Pull request by mmmavis**
### Added
- Added a Made with Code activity kit.
- Added Web Lit Basics II activity kit.
- Updated README.md to include platform specific setup instructions.
- "Help us translate" CTA has been added to the Web Literacy Basics page.

### Changed
- Simplified footer section.

### CODE REVIEW

**Comment by mmmavis** [comment]
@hannahkane r? :grin:

**Comment by hannahkane** [comment]
R+, but are the footer elements supposed to line up
screen shot 2015-12-03 at 1 45 00 pm

**Comment by mmmavis** [comment]
@hannahkane on the mockup they are not /cc @kristinashu what do you think?

**Comment by kristinashu** [comment]
No, they weren't meant to line up. This way it will work no matter what the text is (ie if one is really long).

**Comment by hannahkane** [comment]
Ok. Good to go then.

**Comment by mmmavis** [comment]
YEAH! :tada:

**Comment by hannahkane** [comment]
woohoo!!

**Pull request merged**
